# Generated by Django 2.1a1 on 2018-07-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ManyToManyField(to='conference.paperRecord')),
            ],
        ),
    ]
