# Generated by Django 2.1a1 on 2018-07-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorrecord',
            old_name='organizatoin',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='authorrecord',
            name='authorNumber',
        ),
        migrations.AlterField(
            model_name='paperrecord',
            name='keywords',
            field=models.TextField(max_length=100),
        ),
    ]
