# Generated by Django 2.1a1 on 2018-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20180726_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewpaper',
            old_name='comment',
            new_name='overallEvaluation',
        ),
        migrations.AddField(
            model_name='reviewpaper',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewpaper',
            name='remark',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
