# Generated by Django 2.1a1 on 2018-07-14 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_reviewpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpaper',
            name='paper',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
