# Generated by Django 2.1a1 on 2018-07-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20180714_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpaper',
            name='currentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
