# Generated by Django 2.1a1 on 2018-07-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20180714_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpaper',
            name='currentUser',
        ),
    ]
