# Generated by Django 2.1a1 on 2018-07-14 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0007_remove_reviewpaper_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpaper',
            name='currentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
