# Generated by Django 2.1a1 on 2018-07-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_reviewpaper_currentuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewpaper',
            old_name='paper',
            new_name='paper2',
        ),
    ]
