# Generated by Django 2.1a1 on 2018-07-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20180714_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewpaper',
            old_name='paper2',
            new_name='paper',
        ),
    ]
