# Generated by Django 2.1a1 on 2018-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_commentonpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonpaper',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
