# Generated by Django 2.1a1 on 2018-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
    ]
