# Generated by Django 2.1a1 on 2018-07-23 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0016_auto_20180724_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='reviewPaper',
        ),
    ]
